(cl:defpackage villa_surface_detectors-srv
  (:use )
  (:export
   "DETECTHORIZONTALPLANES"
   "<DETECTHORIZONTALPLANES-REQUEST>"
   "DETECTHORIZONTALPLANES-REQUEST"
   "<DETECTHORIZONTALPLANES-RESPONSE>"
   "DETECTHORIZONTALPLANES-RESPONSE"
  ))

