(cl:in-package villa_surface_detectors-srv)
(cl:export '(CLOUD_INPUT-VAL
          CLOUD_INPUT
          HORIZONTAL_PLANES-VAL
          HORIZONTAL_PLANES
          HORIZONTAL_PLANE_COEFS-VAL
          HORIZONTAL_PLANE_COEFS
          HORIZONTAL_PLANE_BOUNDING_BOXES-VAL
          HORIZONTAL_PLANE_BOUNDING_BOXES
          HORIZONTAL_PLANE_AA_BOUNDING_BOXES-VAL
          HORIZONTAL_PLANE_AA_BOUNDING_BOXES
))