// Generated by gencpp from file villa_surface_detectors/DetectHorizontalPlanes.msg
// DO NOT EDIT!


#ifndef VILLA_SURFACE_DETECTORS_MESSAGE_DETECTHORIZONTALPLANES_H
#define VILLA_SURFACE_DETECTORS_MESSAGE_DETECTHORIZONTALPLANES_H

#include <ros/service_traits.h>


#include <villa_surface_detectors/DetectHorizontalPlanesRequest.h>
#include <villa_surface_detectors/DetectHorizontalPlanesResponse.h>


namespace villa_surface_detectors
{

struct DetectHorizontalPlanes
{

typedef DetectHorizontalPlanesRequest Request;
typedef DetectHorizontalPlanesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectHorizontalPlanes
} // namespace villa_surface_detectors


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanes > {
  static const char* value()
  {
    return "a0f448ffc3cd900d5281565c7c294544";
  }

  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanes&) { return value(); }
};

template<>
struct DataType< ::villa_surface_detectors::DetectHorizontalPlanes > {
  static const char* value()
  {
    return "villa_surface_detectors/DetectHorizontalPlanes";
  }

  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanes&) { return value(); }
};


// service_traits::MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanesRequest> should match 
// service_traits::MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanes > 
template<>
struct MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanes >::value();
  }
  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::villa_surface_detectors::DetectHorizontalPlanesRequest> should match 
// service_traits::DataType< ::villa_surface_detectors::DetectHorizontalPlanes > 
template<>
struct DataType< ::villa_surface_detectors::DetectHorizontalPlanesRequest>
{
  static const char* value()
  {
    return DataType< ::villa_surface_detectors::DetectHorizontalPlanes >::value();
  }
  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanesResponse> should match 
// service_traits::MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanes > 
template<>
struct MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::villa_surface_detectors::DetectHorizontalPlanes >::value();
  }
  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::villa_surface_detectors::DetectHorizontalPlanesResponse> should match 
// service_traits::DataType< ::villa_surface_detectors::DetectHorizontalPlanes > 
template<>
struct DataType< ::villa_surface_detectors::DetectHorizontalPlanesResponse>
{
  static const char* value()
  {
    return DataType< ::villa_surface_detectors::DetectHorizontalPlanes >::value();
  }
  static const char* value(const ::villa_surface_detectors::DetectHorizontalPlanesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VILLA_SURFACE_DETECTORS_MESSAGE_DETECTHORIZONTALPLANES_H
